config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
  get 'welcome/about'
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users

  resources :registered_applications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events

  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  before_action :set_access_control_headers

   def set_access_control_headers

     headers['Access-Control-Allow-Origin'] = '*'

     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'

     headers['Access-Control-Allow-Headers'] = 'Content-Type'
   end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.build(event_params)
        if @event.save
          render json: @event, status: :created
        else
          render json: {errors: @event.errors}, status: :unprocessable_entity
        end
    end

  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @applications = RegisteredApplication.all
  end

  def show
    @application = RegisteredApplication.find(params[:id])
    @events = @application.events.group_by(&:name)

  end

  def new
    @application = RegisteredApplication.new

  end

  def create
    @application = RegisteredApplication.new
    @application.name = params[:registered_application][:name]
    @application.url =params[:registered_application][:url]
    @application.user = current_user

    if @application.save!
      redirect_to @application, notice: "Application was installed successfully."

    else
      flash.now[:alert] = "Error registering application, try again."
      render :new
    end

  end

  def destroy
    @application = RegisteredApplication.find(params[:id])

    if @application.destroy
      flash[:notice] = "\"#{@application.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the app"
      render :show
    end
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", welcome_index_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %> </strong>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>

              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'   %> -
              <%= link_to  "Sign In", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
        </ul>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
  </body>
</html>

app/views/registered_applications/index.html.erb
<h1> All my applications <h1>
<ul>
<% @applications.each do |app| %>
  <li><%= link_to app.name, app %></li>
</ul>
<% end %>

app/views/registered_applications/new.html.erb
<%= form_for @application do |a| %>
  <%= a.label :name %>
  <%= a.text_field :name %>

  <%=a.label :url %>
  <%= a.text_area :url %>

  <%= a.submit "Save" %>
<%end %>

app/views/registered_applications/show.html.erb
<h1> Application Name: <%= @application.name %> <h1>
<h2> Application URL: <%=@application.url %> </h2>

<div class= "col-md-4">
    <%= link_to "delete", @application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>

</div>

<div class= "col-md-4" >
  <% @application.events.group(:name).count.each do |name, count| %>
    <p>Name: <%= name%></p>
    <p> Count: <%= count %> </p>


<% end %>

<%= pie_chart @application.events.group(:name).count %>

<%= line_chart @application.events.group_by_day(:created_at).count %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>